import { createAdapter, directory, file, portableProfile } from "./base.js";

const documentOutput = (path = "AGENTS.md", maxBytes) => ({
  path,
  format: "document",
  ...(maxBytes ? { maxBytes } : {}),
});

const known = [
  createAdapter({
    id: "cursor",
    vendor: "cursor",
    product: "cursor",
    surface: "ide",
    description: "Cursor IDE",
    priority: 100,
    support: "native",
    signals: [
      directory(".cursor"),
      file(".cursor/mcp.json"),
      file(".cursorrules"),
    ],
    outputs: [{ path: ".cursor/rules/agents.mdc", format: "cursor" }],
    capabilities: { scopedRules: true, mcp: true, projectConfig: true },
    documentationUrl: "https://docs.cursor.com/context/rules",
  }),
  createAdapter({
    id: "codex-cli",
    vendor: "openai",
    product: "codex",
    surface: "cli",
    description: "OpenAI Codex CLI",
    priority: 95,
    support: "native",
    signals: [file("AGENTS.md"), directory(".codex")],
    outputs: [documentOutput("AGENTS.md", 32768)],
    skillRoot: ".agents/skills",
    capabilities: {
      agentsMd: true,
      skills: true,
      subagents: true,
      hooks: true,
      mcp: true,
      projectConfig: true,
    },
    documentationUrl:
      "https://developers.openai.com/codex/customization/overview",
  }),
  createAdapter({
    id: "claude-code",
    vendor: "anthropic",
    product: "claude-code",
    surface: "cli",
    description: "Claude Code",
    priority: 90,
    support: "native",
    signals: [file("CLAUDE.md"), directory(".claude")],
    outputs: [documentOutput("CLAUDE.md")],
    skillRoot: ".claude/skills",
    capabilities: {
      skills: true,
      subagents: true,
      mcp: true,
      projectConfig: true,
    },
    documentationUrl: "https://docs.anthropic.com/en/docs/claude-code",
  }),
  createAdapter({
    id: "gemini-cli",
    vendor: "google",
    product: "gemini-cli",
    surface: "cli",
    description: "Gemini CLI",
    priority: 85,
    support: "native",
    signals: [file("GEMINI.md"), directory(".gemini")],
    outputs: [documentOutput("GEMINI.md")],
    capabilities: { projectConfig: true },
    documentationUrl: "https://github.com/google-gemini/gemini-cli",
  }),
  createAdapter({
    id: "pi",
    vendor: "independent",
    product: "pi",
    surface: "cli",
    description: "Pi Coding Agent",
    priority: 80,
    support: "portable",
    signals: [directory(".pi"), file("AGENTS.md"), file("CLAUDE.md")],
    outputs: [documentOutput("AGENTS.md")],
    skillRoot: ".pi/skills",
    capabilities: { agentsMd: true, skills: true, subagents: true },
  }),
  createAdapter({
    id: "openclaw",
    vendor: "openclaw",
    product: "openclaw",
    surface: "cli",
    description: "OpenClaw",
    priority: 75,
    support: "portable",
    signals: [directory(".openclaw"), file("openclaw.json")],
    outputs: [documentOutput("AGENTS.md")],
    skillRoot: "skills",
    capabilities: {
      agentsMd: true,
      skills: true,
      mcp: true,
      subagents: true,
      projectConfig: true,
    },
  }),
  createAdapter({
    id: "hermes",
    vendor: "hermes",
    product: "hermes",
    surface: "cli",
    description: "Hermes Agent",
    priority: 70,
    support: "portable",
    signals: [directory(".hermes"), file("hermes.json"), file("Hermes.md")],
    outputs: [documentOutput("AGENTS.md")],
    skillRoot: "skills",
    capabilities: { agentsMd: true, skills: true },
  }),
  createAdapter({
    id: "copilot",
    vendor: "github",
    product: "copilot",
    surface: "ide",
    description: "GitHub Copilot",
    priority: 65,
    support: "native",
    signals: [
      file(".github/copilot-instructions.md"),
      directory(".github/copilot"),
    ],
    outputs: [documentOutput(".github/copilot-instructions.md")],
    capabilities: { projectConfig: true },
    documentationUrl:
      "https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot",
  }),
  createAdapter({
    id: "cline",
    vendor: "cline",
    product: "cline",
    surface: "ide",
    description: "Cline",
    priority: 60,
    support: "native",
    signals: [file(".clinerules"), directory(".cline")],
    outputs: [documentOutput(".clinerules")],
    capabilities: { mcp: true, projectConfig: true },
  }),
];

const portableAdapters = [
  ["codex-app", "openai", "codex", "desktop"],
  ["openai-agents", "openai", "agents-sdk", "sdk"],
  ["chatgpt-canvas", "openai", "chatgpt", "cloud"],
  ["claude-cli", "anthropic", "claude", "cli"],
  ["claude-desktop", "anthropic", "claude", "desktop"],
  ["anthropic-sdk", "anthropic", "sdk", "sdk"],
  ["gemini-code-assist", "google", "gemini", "ide"],
  ["antigravity", "google", "antigravity", "ide"],
  ["google-jules", "google", "jules", "cloud"],
  ["firebase-studio", "google", "firebase-studio", "cloud"],
  ["windsurf", "codeium", "windsurf", "ide"],
  ["zed", "zed", "zed", "ide"],
  ["continue", "continue", "continue", "ide"],
  ["copilot-vscode", "github", "copilot", "ide"],
  ["copilot-jetbrains", "github", "copilot", "ide"],
  ["junie", "jetbrains", "junie", "ide"],
  ["opencode", "opencode", "opencode", "cli"],
  ["aider", "aider", "aider", "cli"],
  ["goose", "block", "goose", "cli"],
  ["amp", "sourcegraph", "amp", "cli"],
  ["warp", "warp", "warp", "cli"],
  ["gptme", "gptme", "gptme", "cli"],
  ["llm", "independent", "llm", "cli"],
  ["fabric", "independent", "fabric", "cli"],
  ["roo-code", "roo", "roo-code", "ide"],
  ["kilo-code", "kilo", "kilo-code", "ide"],
  ["amazon-q", "amazon", "q-developer", "ide"],
  ["tabnine", "tabnine", "tabnine", "ide"],
  ["sourcegraph-cody", "sourcegraph", "cody", "ide"],
  ["augment-code", "augment", "augment-code", "ide"],
  ["void", "void", "void", "ide"],
].map(([id, vendor, product, surface], index) =>
  createAdapter({
    ...portableProfile,
    id,
    vendor,
    product,
    surface,
    description: `${product} compatibility adapter`,
    priority: 40 - index,
    skillRoot: ["opencode", "goose", "aider"].includes(id)
      ? `.${id}/skills`
      : undefined,
  }),
);

const genericAdapter = createAdapter({
  ...portableProfile,
  id: "generic",
  vendor: "agnostic",
  product: "agents-md",
  surface: "generic",
  description: "AGENTS.md baseline",
  priority: 0,
  signals: [file("AGENTS.md")],
});

export const builtInAdapters = [...known, ...portableAdapters, genericAdapter];

export function getBuiltInAdapter(id) {
  const aliases = { codex: "codex-cli", gemini: "gemini-cli" };
  const canonicalId = aliases[id] ?? id;
  return builtInAdapters.find((adapter) => adapter.id === canonicalId) ?? null;
}
